Traceback (most recent call last):
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\nbclient\client.py", line 778, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\jupyter_core\utils\__init__.py", line 182, in ensure_async
    result = await obj
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\jupyter_client\channels.py", line 315, in get_msg
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\55329\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\nbclient\client.py", line 1001, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\nbclient\client.py", line 802, in _async_poll_for_reply
    error_on_timeout_execute_reply = await self._async_handle_timeout(timeout, cell)
  File "C:\Users\55329\Documents\3.Repos\Rossmann-sales\.envRossmann\lib\site-packages\nbclient\client.py", line 852, in _async_handle_timeout
    raise CellTimeoutError.error_from_timeout_and_cell(
nbclient.exceptions.CellTimeoutError: A cell timed out while it was being executed, after 30 seconds.
The message was: Cell execution timed out.
Here is a preview of the cell contents:
-------------------
['#competition_distance', '#Adicionando uma distancia muito grander para as linhas onde o valor é nulo, aqui estou considerando que o competidor esta tão longe que não era possivel medir sua distancia', '# ou não era significante', '', "df3['competition_distance'] = df3['competition_distance'].apply(lambda x: 200000.0 if math.isnan(x) else x)"]
...
["month_promo = {1: 'Jan',  2: 'Fev',  3: 'Mar',  4: 'Apr',  5: 'May',  6: 'Jun',  7: 'Jul',  8: 'Aug',  9: 'Sept',  10: 'Oct', 11: 'Nov', 12: 'Dec'}", '', "df3['promo_interval'].fillna(0, inplace= True)", "df3['month_promo'] = df3['date'].dt.month.map(month_promo)", "df3['is_promo'] = df3[['promo_interval', 'month_promo']].apply(lambda x: 0 if x['promo_interval'] == 0 else 1 if x['month_promo'] in x['promo_interval'].split(',') else 0, axis =1)"]
-------------------

